In [1]:
import numpy as np

# Step 1: Create a 5x3 array of random integers between 50 and 100
scores = np.random.randint(50, 101, size=(5, 3))

# Step 2: Calculate column-wise mean (mean of each subject)
mean_scores = scores.mean(axis=0)

# Step 3: Subtract the mean from original scores using broadcasting
centered_scores = scores - mean_scores

# Step 4: Print results
print("Original Scores (5 students x 3 subjects):")
print(scores)

print("\nMean Score of Each Subject:")
print(mean_scores)

print("\nCentered Scores (After Broadcasting):")
print(centered_scores)


Original Scores (5 students x 3 subjects):
[[90 82 85]
 [99 60 87]
 [74 91 74]
 [96 78 66]
 [70 51 58]]

Mean Score of Each Subject:
[85.8 72.4 74. ]

Centered Scores (After Broadcasting):
[[  4.2   9.6  11. ]
 [ 13.2 -12.4  13. ]
 [-11.8  18.6   0. ]
 [ 10.2   5.6  -8. ]
 [-15.8 -21.4 -16. ]]
